server:
  port: 2000

spring:
  cloud:
    gateway:
      routes:
        - id: personCmdApi-RegisterUser
          uri: http://localhost:8081/api/v1/createPerson
          predicates:
            - Path=/api/v1/createPerson

        - id: personCmdApi-UpdateUser
          uri: http://localhost:8081/api/v1/updatePerson/**
          predicates:
            - Path=/api/v1/updatePerson/**

        - id: personCmdApi-RemovePerson
          uri: http://localhost:8081/api/v1/removePerson/**
          predicates:
            - Path=/api/v1/removePerson/**

        - id: personQueryApi
          uri: http://localhost:8082/api/v1/personLookup/**
          predicates:
            - Path=/api/v1/personLookup/**